# Generated by Django 6.0.2 on 2026-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
