# Generated by Django 6.0.3 on 2026-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Успешно"),
                    ("failed", "Ошибка"),
                    ("canceled", "Отменён"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_payment_link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату в Stripe",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID цены в Stripe"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID продукта в Stripe"),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии в Stripe",
                max_length=255,
                null=True,
                verbose_name="ID сессии в Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт"), ("stripe", "Оплата через Stripe")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
