# Generated by Django 4.2.2 on 2026-02-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "course_name",
                    models.CharField(
                        help_text="Введите наименование учебного курса",
                        max_length=100,
                        verbose_name="Наименование учебного курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью для учебного курса",
                        null=True,
                        upload_to="lms/previews/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                (
                    "course_description",
                    models.TextField(
                        help_text="Введите описание учебного курса", verbose_name="Описание учебного курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный курс",
                "verbose_name_plural": "Учебные курсы",
                "ordering": ["course_name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "lesson_name",
                    models.CharField(
                        help_text="Введите наименование урока", max_length=100, verbose_name="Наименование урока"
                    ),
                ),
                (
                    "lesson_description",
                    models.TextField(help_text="Введите описание урока", verbose_name="Описание урока"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью для урока",
                        null=True,
                        upload_to="lms/previews/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(help_text="Введите ссылку на видео урока", verbose_name="Ссылка на видео урока"),
                ),
                (
                    "lesson_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите наименование учебного курса к которому относится урок",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="lms.course",
                        verbose_name="Учебный курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["lesson_name", "lesson_course"],
            },
        ),
    ]
