# Generated by Django 6.0.3 on 2026-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения курса",
                verbose_name="Дата последнего обновления",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения урока",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
